// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2-7FQ7y320o1sWHyBre2KAtTB_mjIPWw',
    appId: '1:278932901665:web:fb182313f58f6b696c3860',
    messagingSenderId: '278932901665',
    projectId: 'note-application-crud',
    authDomain: 'note-application-crud.firebaseapp.com',
    storageBucket: 'note-application-crud.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrC9GVR7y2OeSfmINlny6ajoOWT5VN0yg',
    appId: '1:278932901665:android:62a6c2528291ab176c3860',
    messagingSenderId: '278932901665',
    projectId: 'note-application-crud',
    storageBucket: 'note-application-crud.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHwt3dGa54xSEQs2ikpUMiCAb_ESyF1NM',
    appId: '1:278932901665:ios:27de4e05cdedfeb26c3860',
    messagingSenderId: '278932901665',
    projectId: 'note-application-crud',
    storageBucket: 'note-application-crud.firebasestorage.app',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHwt3dGa54xSEQs2ikpUMiCAb_ESyF1NM',
    appId: '1:278932901665:ios:27de4e05cdedfeb26c3860',
    messagingSenderId: '278932901665',
    projectId: 'note-application-crud',
    storageBucket: 'note-application-crud.firebasestorage.app',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2-7FQ7y320o1sWHyBre2KAtTB_mjIPWw',
    appId: '1:278932901665:web:f9f7499cd9c7d6c86c3860',
    messagingSenderId: '278932901665',
    projectId: 'note-application-crud',
    authDomain: 'note-application-crud.firebaseapp.com',
    storageBucket: 'note-application-crud.firebasestorage.app',
  );
}
